### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by Iqmalhakim** [IlluminatiFish/GoogleFormSpammer#2]
how to fix this kind of issue? error 401 unautorize

**Comment by IlluminatiFish** [comment]
Well, generally speaking a HTTP 401 error suggests that you do not have access to view the content, can you send the command you tried, so that I can assist further?

**Comment by Iqmalhakim** [comment]
gfs.py -u \formRespone -r 10 -t 50 --required --no-required

**Comment by Iqmalhakim** [comment]
> Well, generally speaking a HTTP 401 error suggests that you do not have access to view the content, can you send the command you tried, so that I can assist further?

how do we give access to view it?

**Comment by IlluminatiFish** [comment]
> gfs.py -u \formRespone -r 10 -t 50 --required --no-required

Well looking at the command you have used, it appears (depending on whether you redacted the form url) that the URL is incomplete and has a typo it should be `formResponse`.

As per other issues with the command, you only need either the `--required` OR `--no-required` flag in the command.

`--required` will only attempt to fill out the "required" fields that the form needs, while `--no-required` will fill out all possible fields it can find.

**Comment by Iqmalhakim** [comment]
> 

thank you its working great for me

**Comment by Iqmalhakim** [comment]
hello i have same problem again do i type anything wrong

gfs.py -u "
https://docs.google.com/forms/d/e/1FAIpQLSeNRiJmprv7qcWpb5R61FK2bZenT2UNCZDT2Ng1BxeyRXzp6w/formResponse"
-r 10 -t 50
